spring:
  application:
    name: spring-cloud-eureka-client-consumer-ribbon

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka} # 注册中心服务地址