server:
  port: 2222

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HMDOBO/spring-cloud-config-repository.git

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka} # 注册中心服务地址
  instance:
    preferIpAddress: true

encrypt:
  key: didispace
