spring:
  application:
    name: spring-cloud-eureka-client-consumer

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://www.hmdobo.top:8888/eureka} # 注册中心服务地址